### ISSUE TITLE
appreciation 

### ISSUE THREAD

**Issue by christianholman** [MadelineRitchie/nixos-config#1]
Just dropping my appreciation for this config being open. Had been banging my head trying to get a vfio setup working for a long time and your setup worked almost right out of the box, very clean and understandable! Appreciate you!

**Comment by MadelineRitchie** [comment]
I'm very glad to hear that! I still wasn't happy with it when I stopped using NixOS (for now). Most of the credit goes to https://github.com/j-brn/nixos-vfio

**Comment by christianholman** [comment]
Indeed, your repo was the missing documentation for how to use the module:) If you don't mind, what did you switch to? Another declarative setup?

**Comment by MadelineRitchie** [comment]
I got tired of the friction of handling declarative config, and instead I started using Arch with dotbot for dotfile management. Home manager was really the most painful part of it in retrospect. If I were using NixOS again because it's so great for system state, I'd be using dotbot for home management. I'd probably be having a wonderful time! Not switching again until AUR breaks my stuff a few times I suppose

**Comment by MadelineRitchie** [comment]
Another thing, to be honest, is that Arch's documentation is the best in the Linux world, so that's a really strong motivator

**Comment by christianholman** [comment]
Very fair, I'm having the same experience, but something about the idealism keeps me coming back. For what it's worth Nix has at least saved me a few dozen times from completely bricking my installation 😅 dotbot looks promising, thanks for the pointer! Arch documentation is unrivaled
